CREATE DATABASE IF NOT EXISTS galeria;
USE galeria;

CREATE TABLE imagenes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255),
  url VARCHAR(500),
  categoria VARCHAR(100),
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);